books.path=/Users/Works/homeo-books
index.path=/Users/Works/eclipse_workspace/searchhub/lucene-index

logging.level.com.searchhub=DEBUG

management.endpoints.web.exposure.include=health,info, metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=SearchHub
info.app.description=Lucene-based search platform with Spring Boot REST API
info.app.version=1.3.0

spring.datasource.url=jdbc:postgresql://localhost:5432/searchhub
spring.datasource.username=searchhub
spring.datasource.password=searchhub

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true